## Formatting pop_move_csv data  

e-Statのホームページ: https://www.e-stat.go.jp/  
統計データを探す > データベースから探す > 住民基本台帳人口移動報告 >  
 平成29年住民基本台帳人口移動報告 の 年次 > 
表番号005: 都道府県内移動者数，他都道府県からの転入者数及び他都道府県への転出者数－全国，都道府県，21大都市（平成28年，29年）） の右の「DB」ボタン >  
 「ダウンロード」ボタン >  
 全データ、CSV形式、ヘッダ出力、コード出力、桁区切り（,）を使用しない、の設定で 「ダウンロード」
 ==> pop_move_H27_H28_estat.csv

### Import libraries

In [1]:
import pandas as pd

### Parameters

In [2]:
csv_in = 'pop_move_H27_H28_estat.csv' # from e-Stat
csv_out = 'pop_move_H27_H28-utf8.csv'

pd.options.display.max_rows = 999
pd.options.display.max_columns = 999

### Read CSV file for check

In [3]:
df = pd.read_csv(csv_in, delimiter='\n', dtype='object',
                 skiprows=None, header=None, encoding='shift-jis')
print(df.shape)
display(df.head(15))

(81, 1)

                                                    0
0               統計名：,"住民基本台帳人口移動報告 平成28年住民基本台帳人口移動報告"
1                                          表番号：,"005"
2   表題：,"都道府県内移動者数，他都道府県からの転入者数及び他都道府県への転出者数−全国，都道...
3                                   実施年月：,"2016年","-"
4                                    市区町村時点（年月日）：,"-"
5                            ***,"調査していないため該当数値がないもの"
6                                    -,"定義上該当数値がないもの"
7   ,"","","","","001","","001","","001","","002",...
8   ,"","","","/実数・移動率・日本人人口","実数　都道府県（自都市）内移動者","...
9   ,"","","","","050","","054","","057","","050",...
10  国籍 コード,"国籍","全国・都道府県・大都市4 コード","全国・都道府県・大都市4",...
11  61000,"日本人移動者","00000","全国","","2706745","","2...
12  61000,"日本人移動者","01000","北海道","","199448","","1...
13  61000,"日本人移動者","02000","青森県","","17531","","16...
14  61000,"日本人移動者","03000","岩手県","","19337","","18...

### Re-read CSV: set delimiter as ',', skip 10 lines and read header  
Set dtype automatically

In [4]:
df = pd.read_csv(csv_in, delimiter=',',
                 skiprows=10, header=0, encoding='shift-jis')
print(df.shape)
display(df.head(5))

(72, 59)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,/実数・移動率・日本人人口,実数 都道府県（自都市）内移動者,Unnamed: 6,実数 都道府県（自都市）内移動者.1,Unnamed: 8,実数 都道府県（自都市）内移動者.2,Unnamed: 10,実数 他都道府県（他市町村）からの転入者,Unnamed: 12,実数 他都道府県（他市町村）からの転入者.1,Unnamed: 14,実数 他都道府県（他市町村）からの転入者.2,Unnamed: 16,実数 他都道府県（他市町村）への転出者,Unnamed: 18,実数 他都道府県（他市町村）への転出者.1,Unnamed: 20,実数 他都道府県（他市町村）への転出者.2,Unnamed: 22,実数 転入超過,Unnamed: 24,実数 転入超過.1,Unnamed: 26,実数 転入超過.2,Unnamed: 28,移動率 都道府県（自都市）内移動者【％】,Unnamed: 30,移動率 都道府県（自都市）内移動者【％】.1,Unnamed: 32,移動率 都道府県（自都市）内移動者【％】.2,Unnamed: 34,移動率 他都道府県（他市町村）からの転入者【％】,Unnamed: 36,移動率 他都道府県（他市町村）からの転入者【％】.1,Unnamed: 38,移動率 他都道府県（他市町村）からの転入者【％】.2,Unnamed: 40,移動率 他都道府県（他市町村）への転出者【％】,Unnamed: 42,移動率 他都道府県（他市町村）への転出者【％】.1,Unnamed: 44,移動率 他都道府県（他市町村）への転出者【％】.2,Unnamed: 46,移動率 転入超過【％】,Unnamed: 48,移動率 転入超過【％】.1,Unnamed: 50,移動率 転入超過【％】.2,Unnamed: 52,日本人人口【千人】,Unnamed: 54,日本人人口【千人】.1,Unnamed: 56,日本人人口【千人】.2,Unnamed: 58
0,NaN,NaN,NaN,NaN,NaN,050,NaN,054,NaN,057,NaN,050,NaN,054,NaN,057,NaN,050,NaN,054,NaN,057,NaN,050,NaN,054,NaN,057,NaN,050,NaN,054,NaN,057,NaN,050,NaN,054,NaN,057,NaN,050,NaN,054,NaN,057,NaN,050,NaN,054,NaN,057,NaN,050,NaN,054,NaN,057,NaN
1,国籍 コード,国籍,全国・都道府県・大都市4 コード,全国・都道府県・大都市4,/推移2,平成２７年,注釈,平成２８年,注釈,平成２７年〜２８年の増減,注釈,平成２７年,注釈,平成２８年,注釈,平成２７年〜２８年の増減,注釈,平成２７年,注釈,平成２８年,注釈,平成２７年〜２８年の増減,注釈,平成２７年,注釈,平成２８年,注釈,平成２７年〜２８年の増減,注釈,平成２７年,注釈,平成２８年,注釈,平成２７年〜２８年の増減,注釈,平成２７年,注釈,平成２８年,注釈,平成２７年〜２８年の増減,注釈,平成２７年,注釈,平成２８年,注釈,平成２７年〜２８年の増減,注釈,平成２７年,注釈,平成２８年,注釈,平成２７年〜２８年の増減,注釈,平成２７年,注釈,平成２８年,注釈,平成２７年〜２８年の増減,注釈
2,61000,日本人移動者,00000,全国,NaN,2706745,NaN,2605636,NaN,-101109,NaN,2334738,NaN,2275331,NaN,-59407,NaN,2334738,NaN,2275331,NaN,-59407,NaN,0,NaN,0,NaN,0,NaN,2.16,NaN,2.08,NaN,***,NaN,1.86,NaN,1.82,NaN,***,NaN,1.86,NaN,1.82,NaN,***,NaN,0.00,NaN,0.00,NaN,***,NaN,125319,NaN,125020,NaN,***,NaN
3,61000,日本人移動者,01000,北海道,NaN,199448,NaN,192225,NaN,-7223,NaN,47584,NaN,48544,NaN,960,NaN,56446,NaN,55418,NaN,-1028,NaN,-8862,NaN,-6874,NaN,1988,NaN,3.72,NaN,3.61,NaN,***,NaN,0.89,NaN,0.91,NaN,***,NaN,1.05,NaN,1.04,NaN,***,NaN,-0.17,NaN,-0.13,NaN,***,NaN,5360,NaN,5327,NaN,***,NaN
4,61000,日本人移動者,02000,青森県,NaN,17531,NaN,16577,NaN,-954,NaN,17724,NaN,17061,NaN,-663,NaN,24284,NaN,23384,NaN,-900,NaN,-6560,NaN,-6323,NaN,237,NaN,1.34,NaN,1.29,NaN,***,NaN,1.36,NaN,1.32,NaN,***,NaN,1.86,NaN,1.81,NaN,***,NaN,-0.50,NaN,-0.49,NaN,***,NaN,1305,NaN,1290,NaN,***,NaN

### Select columns we need

In [5]:
df_diff = df[['Unnamed: 3', '実数　他都道府県（他市町村）からの転入者.1', '実数　他都道府県（他市町村）への転出者.1']]
print(df_diff.shape)
print(df_diff.info())
print(df_diff)

(72, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 3 columns):
Unnamed: 3                71 non-null object
実数　他都道府県（他市町村）からの転入者.1    72 non-null object
実数　他都道府県（他市町村）への転出者.1     72 non-null object
dtypes: object(3)
memory usage: 1.8+ KB
None
      Unnamed: 3 実数　他都道府県（他市町村）からの転入者.1 実数　他都道府県（他市町村）への転出者.1
0            NaN                    054                   054
1   全国・都道府県・大都市4                  平成２８年                 平成２８年
2             全国                2275331               2275331
3            北海道                  48544                 55418
4            青森県                  17061                 23384
5            岩手県                  17113                 20983
6            宮城県                  47124                 47607
7            秋田県                  11353                 15751
8            山形県                  12921                 16560
9            福島県                  25505                 31344
10           茨城県                  45166                 48875
11           栃木県                  29760                 32748
12           群馬県                  26344                 29080
13           埼玉県                 159389                143829
14           千葉県                 143081                127006
15           東京都                 413444                339267
16          神奈川県                 205368                193312
17           新潟県                  21316                 27505
18           富山県                  12206                 13210
19           石川県                  17519                 18330
20           福井県                   8557                 10377
21           山梨県                  12366                 14377
22           長野県                  25765                 28445
23           岐阜県                  25459                 30490
24           静岡県                  49211                 55601
25           愛知県                 111160                104895
26           三重県                  25728                 29325
27           滋賀県                  24656                 25362
28           京都府                  53759                 54509
29           大阪府                 152537                150743
30           兵庫県                  85933                 92693
31           奈良県                  23004                 26623
32          和歌山県                  10681                 14575
33           鳥取県                   8672                  9982
34           島根県                  10248                 11500
35           岡山県                  28054                 30027
36           広島県                  45966                 48102
37           山口県                  21394                 25195
38           徳島県                   9107                 10855
39           香川県                  16937                 18038
40           愛媛県                  17080                 20727
41           高知県                   8919                 11184
42           福岡県                  98344                 92612
43           佐賀県                  14831                 17131
44           長崎県                  22105                 27678
45           熊本県                  26003                 32794
46           大分県                  17852                 20460
47           宮崎県                  17404                 21692
48          鹿児島県                  25811                 30284
49           沖縄県                  24574                 24846
50        21大都市計                1263682               1157865
51           札幌市                  62960                 53823
52           仙台市                  42551                 41585
53         さいたま市                  52542                 43887
54           千葉市                  33617                 32751
55       東京都特別区部                 354701                296494
56           横浜市                 114062                111151
57           川崎市                  74053                 67214
58          相模原市                  23034                 23439
59           新潟市                  16837                 17208
60           静岡市                  15722                 16533
61           浜松市                  15915                 16521
62          名古屋市                  79730                 73780
63           京都市                  41198                 40608
64           大阪市                  97494                 88020
65            堺市                  21600                 22806
66           神戸市                  41125                 41367
67           岡山市                  21525                 21139
68           広島市                  36021                 34852
69          北九州市                  23604                 26227
70           福岡市                  70792                 62321
71           熊本市                  24599                 26139

### Drop top 3 lines, reset columns

In [6]:
df_diff2 = df_diff.loc[3:].reset_index(drop=True)
df_diff2.columns = ['都道府県', '転入', '転出']
print(df_diff2.shape)
print(df_diff2.info())
print(df_diff2)

(69, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69 entries, 0 to 68
Data columns (total 3 columns):
都道府県    69 non-null object
転入      69 non-null object
転出      69 non-null object
dtypes: object(3)
memory usage: 1.7+ KB
None
       都道府県       転入       転出
0       北海道    48544    55418
1       青森県    17061    23384
2       岩手県    17113    20983
3       宮城県    47124    47607
4       秋田県    11353    15751
5       山形県    12921    16560
6       福島県    25505    31344
7       茨城県    45166    48875
8       栃木県    29760    32748
9       群馬県    26344    29080
10      埼玉県   159389   143829
11      千葉県   143081   127006
12      東京都   413444   339267
13     神奈川県   205368   193312
14      新潟県    21316    27505
15      富山県    12206    13210
16      石川県    17519    18330
17      福井県     8557    10377
18      山梨県    12366    14377
19      長野県    25765    28445
20      岐阜県    25459    30490
21      静岡県    49211    55601
22      愛知県   111160   104895
23      三重県    25728    29325
24      滋賀県    24656    25362
25      京都府    53759    54509
26      大阪府   152537   150743
27      兵庫県    85933    92693
28      奈良県    23004    26623
29     和歌山県    10681    14575
30      鳥取県     8672     9982
31      島根県    10248    11500
32      岡山県    28054    30027
33      広島県    45966    48102
34      山口県    21394    25195
35      徳島県     9107    10855
36      香川県    16937    18038
37      愛媛県    17080    20727
38      高知県     8919    11184
39      福岡県    98344    92612
40      佐賀県    14831    17131
41      長崎県    22105    27678
42      熊本県    26003    32794
43      大分県    17852    20460
44      宮崎県    17404    21692
45     鹿児島県    25811    30284
46      沖縄県    24574    24846
47   21大都市計  1263682  1157865
48      札幌市    62960    53823
49      仙台市    42551    41585
50    さいたま市    52542    43887
51      千葉市    33617    32751
52  東京都特別区部   354701   296494
53      横浜市   114062   111151
54      川崎市    74053    67214
55     相模原市    23034    23439
56      新潟市    16837    17208
57      静岡市    15722    16533
58      浜松市    15915    16521
59     名古屋市    79730    73780
60      京都市    41198    40608
61      大阪市    97494    88020
62       堺市    21600    22806
63      神戸市    41125    41367
64      岡山市    21525    21139
65      広島市    36021    34852
66     北九州市    23604    26227
67      福岡市    70792    62321
68      熊本市    24599    26139

### Save to CSV file

In [7]:
df_diff2.to_csv(csv_out, index=False)